# Generated by Django 5.2.9 on 2025-12-17 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(
                        choices=[("usd", "USD"), ("mxn", "MXN")], max_length=3
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("single_broker_sale", "Single broker sale"),
                            (
                                "double_broker_commission_split",
                                "Double broker commission split",
                            ),
                            ("due_diligence", "Due diligence"),
                            ("hidden_defects", "Hidden defects"),
                        ],
                        max_length=64,
                    ),
                ),
                ("property_type", models.CharField(max_length=255)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "earnest_deposit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("due_diligence_end_date", models.DateField()),
                ("estimated_closing_date", models.DateField()),
                (
                    "initiating_party_role",
                    models.CharField(
                        blank=True,
                        choices=[("buyer", "Buyer"), ("seller", "Seller")],
                        help_text="For double broker transactions, records whether the original broker knows the buyer or seller.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("primary_broker", "Primary broker"),
                            ("secondary_broker", "Secondary broker"),
                            ("participant", "Participant"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("transaction", "email", "role")},
            },
        ),
    ]
