# Generated by Django 5.2.9 on 2025-12-18 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="depositor_name",
            field=models.CharField(
                blank=True,
                help_text="Only required if depositor is not the purchaser",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_diligence_end_date",
            field=models.DateField(default=datetime.date(2025, 12, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="earnest_deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="estimated_closing_date",
            field=models.DateField(default=datetime.date(2025, 12, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="property_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
