# Generated by Django 5.2.9 on 2025-12-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_depositor_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="stage",
            field=models.CharField(
                choices=[
                    ("pending_invitations", "Pending Invitations"),
                    ("pending_user_information", "Pending User Information"),
                ],
                default="pending_invitations",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stage_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stage_changed", "Stage Changed"),
                            ("invitation_sent", "Invitation Sent"),
                            ("invitation_accepted", "Invitation Accepted"),
                            ("counterparty_invited", "Counterparty Invited"),
                        ],
                        max_length=64,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
